# 日志
logging:
  config: classpath:log4j.xml
  level:
    cn:
      gdpu:
        mapper: debug

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*DAO.xml
  type-aliases-package: cn.gdpu.bean

# 端口限定
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  main:
    allow-bean-definition-overriding: true

  resources:
    static-locations: classpath:/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8
    request-context-attribute: req
    enabled: false
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: MyHikariCP
    url: jdbc:mysql://localhost:3306/online_course_selection_system?useSSL=false&characterEncoding=UTF-8
    username: your_username
    password: your_password

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    cache: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
      force-request: true

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 300
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
